canine class I: 1.2
canine class II 1-2: 1.5
canine class II 3-4: 1.3
canine class II full class: 2.5
canine class III 1-2: 3.5
canine class III 1-4: 1.0
canine-class-III-full-class: 1.0
molar class I: 1.0
molar class II 1-2: 1.8
molar class II 1-4: 3.0
molar class II 3-4: 2.5
molar class II full class: 1.0
molar class III 1-2: 1.0
molar class III 1-4: 1.5
