amp: true
auto_augment: randaugment
batch: 16
box: 7.5
cache: false
close_mosaic: 10
cls: 3.0
copy_paste: 0.2
copy_paste_mode: flip
cos_lr: false
cutmix: 0.0
data: data.yaml
degrees: 10.0
deterministic: true
device: '0'
dfl: 1.5
dropout: 0.0
epochs: 150
erasing: 0.4
exist_ok: false
fliplr: 0.2
flipud: 0.0
fraction: 1.0
freeze: null
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 800
lr0: 0.003
lrf: 0.01
mask_ratio: 4
mixup: 0.2
model: yolo11s.pt
momentum: 0.95
mosaic: 1.0
multi_scale: false
name: phase1_run
optimizer: auto
overlap_mask: true
patience: 25
perspective: 0.0
pretrained: true
profile: false
project: main_dataset_optimized
rect: false
resume: false
save: true
save_period: 25
scale: 0.3
seed: 0
shear: 0.0
single_cls: false
split: val
translate: 0.15
val: true
verbose: true
warmup_bias_lr: 0.05
warmup_epochs: 7
warmup_momentum: 0.8
weight_decay: 0.0015
workers: 8
