amp: true
auto_augment: randaugment
batch: 16
box: 7.5
cache: false
close_mosaic: 10
cls: 3.5
copy_paste: 0.15
copy_paste_mode: flip
cos_lr: false
cutmix: 0.0
data: data.yaml
degrees: 5.0
deterministic: true
device: '0'
dfl: 1.5
dropout: 0.0
epochs: 200
erasing: 0.3
exist_ok: false
fliplr: 0.3
flipud: 0.0
fraction: 1.0
freeze: null
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 800
lr0: 0.005
lrf: 0.01
mask_ratio: 4
mixup: 0.15
model: yolo11s.pt
momentum: 0.95
mosaic: 1.0
multi_scale: false
name: phase2_run
optimizer: auto
overlap_mask: true
patience: 30
perspective: 0.0
pretrained: true
profile: false
project: main_dataset_optimized
rect: false
resume: false
save: true
save_period: 25
scale: 0.2
seed: 42
shear: 0.0
single_cls: false
split: val
translate: 0.1
val: true
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 5
warmup_momentum: 0.8
weight_decay: 0.0015
workers: 8
